version: '3.3'

services:
  jwt-grant-performance:
    image: ${REGISTRY}/jwt-grant-performance:${VERSION}
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
networks:
  atest:
    driver: overlay
    attachable: true

